sudo: false
language: java
script: ./mvnw clean verify
jdk:
  - openjdk8
after_success:
  - if [ $SONATYPE_USERNAME ] && [ -z $TRAVIS_TAG ] && [ "$TRAVIS_BRANCH" = "master" ]; then
      mvn clean deploy --settings .travis/settings.xml;
      echo "Finished mvn clean deploy for $TRAVIS_BRANCH";
    fi;
branches:
  only:
  - master